openapi: 3.0.0
info:
  title: Tifin-Service API 2
  version: 1.0.0
tags:
  - name: Authentication
    description: APIs related to authentication
  - name: Users
    description: APIs related to users
  - name: Settings
    description: APIs related to settings
  - name: Utils
    description: APIs related to utils
components:
  securitySchemes:
    Token-Authentication:
      type: http
      scheme: bearer
paths:

  /auth/sign-up:
    post:
      tags:
        - Authentication
      summary: Registers a new user
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - countryCode
                - mobile
              properties:
                countryCode:
                  type: string
                mobile:
                  type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
    
  /auth/resend-otp:
    post:
      tags:
        - Authentication
      summary: Resends an OTP to the user's phone number
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - mobile
              properties:
                mobile:
                  type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  
  /auth/varify-otp:
    post:
      tags:
        - Authentication
      summary: Verifies the OTP sent to the user's phone number
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - mobile
                - token
                - otp
              properties:
                mobile:
                  type: string
                otp:
                  type: number
                token:
                  type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized

  /auth/log-out:
    get:
      tags:
        - Authentication
      summary: Logout current user
      security:
        - Token-Authentication: []
      responses:
        '200':
          description: OK
  
  /users/profile:
    get:
      tags:
        - Users
      summary: Retrieves user data
      security:
        - Token-Authentication: []
      responses:
        '200':
          description: OK

  /users/update-profile:
    post:
      tags:
        - Users
      summary: Updates the current user's profile
      security:
        - Token-Authentication: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  
  /setting/:
    get:
      tags:
        - Settings
      summary: Retrieves system settings
      security:
        - Token-Authentication: []
      responses:
        '200':
          description: OK
  
  /util/upload-file:
    post:
      tags:
        - Utils
      summary: upload photo function
      security:
        - Token-Authentication: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - extension
                - directory
              properties:
                extension:
                  type: string
                  example: 'png'
                directory:
                  type: string
                  example: '/users'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  
  /util/delete-file:
    post:
      tags:
        - Utils
      summary: delete photo function
      security:
        - Token-Authentication: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - extension
                - directory
              properties:
                extension:
                  type: string
                  example: 'png'
                directory:
                  type: string
                  example: '/users'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  