swagger: '2.0'
info:
  title: My API
  version: 1.0.0
tags:
  - name: Authentication
    description: APIs related to authentication
  - name: Users
    description: APIs related to users
  - name: Settings
    description: APIs related to settings
  - name: Utils
    description: APIs related to utils
paths:
  /login:
    post:
      tags:
        - Authentication
      summary: Logs a user into the system
      parameters:
        - name: username
          in: formData
          required: true
          type: string
        - name: password
          in: formData
          required: true
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  
  /sign-up:
    post:
      tags:
        - Authentication
      summary: Logs a user into the system
      parameters:
        - name: username
          in: formData
          required: true
          type: string
        - name: password
          in: formData
          required: true
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
    
  /forget-password:
    post:
      tags:
        - Authentication
      summary: Logs a user into the system
      parameters:
        - name: username
          in: formData
          required: true
          type: string
        - name: password
          in: formData
          required: true
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  
  /resend-otp:
    post:
      tags:
        - Authentication
      summary: Logs a user into the system
      parameters:
        - name: username
          in: formData
          required: true
          type: string
        - name: password
          in: formData
          required: true
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  
  /varify-otp:
    post:
      tags:
        - Authentication
      summary: Logs a user into the system
      parameters:
        - name: username
          in: formData
          required: true
          type: string
        - name: password
          in: formData
          required: true
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  

  /profile:
    get:
      tags:
        - Users
  
  /update-profile:
    post:
      tags:
        - Users
      summary: Logs a user into the system
      parameters:
        - name: username
          in: formData
          required: true
          type: string
        - name: password
          in: formData
          required: true
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  


  /settings:
    get:
      tags:
        - Settings
      summary: Retrieves system settings
      responses:
        '200':
          description: OK
